README.md
prisma/migrations/20220210161240_rename_newtab_to_scheduledsurface/migration.sql
prisma/schema.prisma
prisma/seed.ts
schema-admin.graphql
src/admin/resolvers/index.ts
src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/ApprovedItem.ts
src/admin/resolvers/mutations/ScheduledItem.integration.ts
src/admin/resolvers/mutations/ScheduledItem.ts
src/admin/resolvers/queries/ScheduledItem.integration.ts
src/admin/resolvers/queries/ScheduledItem.ts
src/admin/resolvers/queries/ScheduledSurface.integration.ts
src/admin/resolvers/queries/ScheduledSurface.ts
src/admin/resolvers/queries/sample-queries.gql.ts
src/database/mutations/ScheduledItem.ts
src/database/queries/ScheduledItem.ts
src/database/types.ts
src/events/curatedCorpusEventEmitter.spec.ts
src/events/snowplow/ScheduledItemSnowplowHandler.integration.ts
src/events/snowplow/ScheduledItemSnowplowHandler.ts
src/events/snowplow/schema.ts
src/events/types.ts
src/public/resolvers/queries/ScheduledSurface.integration.ts
src/public/resolvers/queries/ScheduledSurface.ts
src/public/resolvers/queries/ScheduledSurfaceItem.integration.ts
src/public/resolvers/queries/ScheduledSurfaceItem.ts
src/shared/types.ts
src/test/helpers/createScheduledItemHelper.integration.ts
src/test/helpers/createScheduledItemHelper.ts

rename new tab to scheduled surface. update other shared data constructs.
- customized migration to get around mysql fk issue
- removed legacy NewTabFeed resolver
no functionality was changed, no tests were changed. the biggest question mark here is the db migration. locally, this required my db to be emptied. as we aren't in prod yet, i don't think this is a big risk, but wanted to call it out. definitely open to ideas there.
note that this will break the frontend, as the API has changed to reflect shared data. we should coordinate a frontend PR and deploy the two together.
- db migration
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1308

refactor(shared data): rename new tab to scheduled surface

---

src/admin/resolvers/queries/ScheduledItem.integration.ts
src/database/queries/ScheduledItem.ts

fix a bug where an empty string could be passed in for `scheduledSurfaceGuid`, resulting in scheduled items being returned for _all_ scheduled surfaces.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1314

fix(query): validate scheduledSurfaceGuid on getScheduledCuratedCorpusItems

---

schema-admin.graphql
src/shared/types.ts

updating shared data based on matt cooper's latest ML work.
- add `DOMAIN_ALLOWLIST` as a `ProspectType`
- associate `DOMAIN_ALLOWLIST` with `NEW_TAB_DE_DE` scheduled surface
Slack:
* https://pocket.slack.com/archives/CTLKW5WCF/p1644938746449939

chore(shared data): update prospect types & new tab de_de

---

src/admin/context.ts
src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/RejectedItem.integration.ts
src/admin/resolvers/mutations/ScheduledItem.integration.ts
src/admin/resolvers/mutations/ScheduledItem.ts
src/admin/resolvers/queries/ScheduledItem.integration.ts
src/database/queries/ScheduledItem.ts
src/public/resolvers/queries/ScheduledSurface.integration.ts
src/shared/types.ts
src/test/helpers/getServerWithMockedHeaders.ts

- Improved auth user context with more convenience props (heavily inspired by the approach taken in Prospect API).
- Added access control checks to `createScheduledItem` and `deleteScheduledItem` mutations.
- Updated existing tests. Added new integration tests that test various user privilege scenarios.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1173

feat(auth): Add access control checks to ScheduledItem mutations [BACK-1173]

---

src/config/index.ts
src/events/snowplow/ScheduledItemSnowplowHandler.integration.ts
src/events/snowplow/ScheduledItemSnowplowHandler.ts
src/events/snowplow/schema.ts

update snowplow schema to use `scheduled_surface` instead of `new_tab`.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1318
Slack thread:
* https://pocket.slack.com/archives/CTLKW5WCF/p1644956989056359

chore(snowplow): update schema to use scheduled surface

---

src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/ApprovedItem.ts

JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1325

feat(auth): Add access checks around creating a corpus item [BACK-1325]

---

src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/ApprovedItem.ts

This is fairly straightforward. As long as the user has write access to the corpus, they should be able to upload images to S3. 
- Added an authentication check to the mutation.
- Added an integration test.
JIRA ticket: https://getpocket.atlassian.net/browse/BACK-1346

feat(auth): Add auth check to `uploadApprovedItemImage` mutation [BACK-1346]

---

src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/ApprovedItem.ts
src/admin/resolvers/mutations/RejectedItem.integration.ts
src/admin/resolvers/mutations/RejectedItem.ts
src/shared/types.ts

prevent invalid `Topic` and `RejectionReason` values from making it into the db.
- not-very-DRY code. should these checks go into a helper?
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1351

fix(validation): validate topic and rejection reason enums on mutations

---

src/admin/resolvers/queries/RejectedItem.auth.integration.ts
src/admin/resolvers/queries/RejectedItem.integration.ts
src/admin/resolvers/queries/RejectedItem.ts

- Added authentication checks to `getRejectedCuratedCorpusItems` query.
- Added auth-related integration tests.
- Added mock headers to existing tests for Rejected Item queries so that they keep passing after the change.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1343

feat(auth): [BACK-1343] Add auth to `getRejectedCuratedCorpusItems` query

---

package.json
src/admin/resolvers/queries/ScheduledItem.auth.integration.ts
src/admin/resolvers/queries/ScheduledItem.integration.ts
src/admin/resolvers/queries/ScheduledItem.ts

Added auth check to `getScheduledCuratedCorpusItems` query. 
Added new tests in the separate `auth.integration` test file. 
Updated current tests
JIRA ticket:
* [BACK-1344]
[BACK-1344]: https://getpocket.atlassian.net/browse/BACK-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(auth): [BACK-1344] add auth to `getScheduledCuratedCorpusItems` query

---

schema-admin.graphql
src/admin/resolvers/index.ts
src/admin/resolvers/mutations/ScheduledItem.integration.ts
src/admin/resolvers/mutations/ScheduledItem.ts
src/admin/resolvers/mutations/sample-mutations.gql.ts
src/database/mutations/ScheduledItem.ts
src/database/mutations/index.ts
src/database/types.ts
src/events/snowplow/types.ts
src/events/types.ts

add a mutation for rescheduling a scheduled item
- remove superfluous server start/stop calls in test file
- add a new snowplow type for reschedule
- refactor delete scheduled item a bit to be more effecient
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1354

feat(mutation): add mutation for rescheduling a scheduled item

---

src/admin/server.ts

To fix a bug - "when you try to add an item to the corpus that is in the rejected corpus, you get an INTERNAL_SERVER_ERROR. we should display a helpful error message instead."
The error handler from `apollo-utils` masks errors that we want to expose to end users (aka the Curation Tools Frontend) of the admin subgraph. Removing the error handler appears to be the most sensible option.
Note that integration tests were and are passing unchanged as they use a separate admin server bootstrap script without the Sentry plugin and that script was never updated to use the error handler, so the bug was not discovered until testing the frontend functionality made it apparent.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1360

fix: [BACK-1360] Fix indecipherable error messages

---

schema-admin.graphql
src/admin/resolvers/index.ts
src/admin/resolvers/queries/ApprovedItem.integration.ts
src/admin/resolvers/queries/sample-queries.gql.ts

- Approved item can now be resolved via the `url` field in other subgraphs.
- Data loaders are not required as Prisma does the heavy lifting for us.
- Tests added for the new reference resolver.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1365

feat(federation): [BACK-1365] make approved curated item available in the admin graph via federation

---

src/admin/aws/utils.ts

make node fetch ignore https error
e.g this image: https://static.hollywoodreporter.com/wp-content/uploads/2021/04/MG_5536-2-SPLASH-2021-1617664574-1024x576.jpg
sentry error: https://sentry.io/organizations/pocket/issues/3129328587/events/c6a1b902daaa4b71a2bdbdab5c1d362b/?environment=development&project=5938284&statsPeriod=1h

make node fetch to ignore https error

---

src/config/index.ts
src/events/eventBus/EventBusConfig.ts
src/events/eventBus/EventBusHandler.spec.ts

Implement remove-schedule-item event
- 
- Reusing the payload transformer since the event body is always the same
JIRA ticket:
* [INFRA-357]
Documentation:
* [Project doc](https://getpocket.atlassian.net/wiki/spaces/CP/pages/2648178701/Curation+Migration+DataSync+Events)
[INFRA-357]: https://getpocket.atlassian.net/browse/INFRA-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(events): Send remove-schedule-item event to event bridge

---

schema-admin.graphql
src/admin/resolvers/index.ts
src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/ApprovedItem.ts
src/admin/resolvers/mutations/RejectedItem.integration.ts
src/admin/resolvers/mutations/ScheduledItem.integration.ts
src/admin/resolvers/mutations/sample-mutations.gql.ts
src/admin/resolvers/queries/ApprovedItem.auth.integration.ts
src/admin/resolvers/queries/ApprovedItem.integration.ts
src/admin/resolvers/queries/RejectedItem.auth.integration.ts
src/admin/resolvers/queries/RejectedItem.integration.ts
src/admin/resolvers/queries/ScheduledItem.auth.integration.ts
src/admin/resolvers/queries/ScheduledItem.integration.ts
src/admin/resolvers/queries/sample-queries.gql.ts
src/admin/resolvers/types.ts
src/shared/fragments.gql.ts

**DO NOT MERGE** until accompanying tickets for the frontend and Prospect API are ready to go.
Take `Curated` out of schema definitions as there's going to be only one Pocket corpus.
- Updated admin schema.
- Updated sample mutations and queries used for integration tests.
- Updated tests.
Note that Apollo check failures are expected. Once the PR is okay'd generally, these changes can be marked as safe and the checks re-run.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1319

chore: [BACK-1319] Remove `Curated` from query and mutation names

---

schema-admin.graphql

Even after a successful deployment of individual subgraphs related to dropping the word `Curated` from all entities, composition checks still fail. @kschelonka has suggested during our pairing that we should have duplicated the affected types instead - bringing `ApprovedCuratedCorpusItem` back temporarily should do the trick.
Follow-up to https://getpocket.atlassian.net/browse/BACK-1319

fix(federation): Temporarily restore ApprovedCuratedCorpusItem

---

src/admin/aws/upload.integration.ts
src/admin/aws/utils.spec.ts
src/admin/aws/utils.ts
src/admin/resolvers/mutations/ApprovedItem.integration.ts

Use the pocket-image-cache service for all URLs except ones that are already pocket-image-cache URLs
JIRA ticket: INFRA-400

fix(images): use pocket-image-cache when possible

---

src/config/index.ts
src/events/eventBus/EventBusConfig.ts
src/events/eventBus/EventBusHandler.spec.ts
src/events/types.ts

Send update events for scheduled + approved items.
Since the application emits two different kinds of events for updating (updating the scheduled item's date/surface vs. the underlying item's fields), we handle them as separate events for event bridge.
Since the legacy system does not have a concept of an approved item that isn't scheduled, It is up to the event subscriber to determine whether it needs to process changes to an approved item.
- all
- Not refactoring the types, although at this time only approved items (and not a union of approved + rejected) are included as a payload on the update event
JIRA ticket:
* [INFRA-356]
Documentation:
* [Project doc](https://getpocket.atlassian.net/wiki/spaces/CP/pages/2648178701/Curation+Migration+DataSync+Events)
[INFRA-356]: …

feat(events): update events

---

src/admin/aws/utils.spec.ts
src/admin/aws/utils.ts

encode the path and query params in the imageUrl
- some of the images were failing coz the query params were not encoded, adding a fix to this
JIRA ticket:
https://getpocket.atlassian.net/browse/INFRA-339

fix(importApprovedCorpusMutation): encode the image_url

---

src/events/eventBus/EventBusConfig.ts
src/events/eventBus/EventBusHandler.spec.ts
src/events/types.ts

Rename event properties to match expectations in data sync service:
`scheduledItemId` => `scheduledItemExternalId`
`approvedItemId` => `approvedItemExternalId`
JIRA ticket: INFRA-393

fix: rename event bus payload property

---

src/events/eventBus/EventBusConfig.ts
src/events/eventBus/EventBusHandler.spec.ts
src/events/types.ts

Rename event property `approvedItem` -> `approvedItemExternalId`
JIRA ticket: INFRA-393

fix: rename event bus payload property approvedItemId -> approvedItemExternalId

---

src/admin/resolvers/queries/ScheduledItem.integration.ts
src/database/queries/ScheduledItem.ts
src/public/resolvers/queries/ScheduledSurfaceItem.integration.ts

sort scheduled items by `updatedAt 'asc'`.
- sorting for both admin and public queries
- do we need both public and admin queries sorted?
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1391

feat(scheduledItem): sort scheduled items by createdAt asc

---

src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/ApprovedItem.ts
src/admin/resolvers/mutations/RejectedItem.integration.ts
src/admin/resolvers/mutations/RejectedItem.ts
src/admin/resolvers/mutations/ScheduledItem.integration.ts
src/admin/resolvers/mutations/ScheduledItem.ts
src/admin/resolvers/queries/ApprovedItem.auth.integration.ts
src/admin/resolvers/queries/ApprovedItem.ts
src/admin/resolvers/queries/RejectedItem.auth.integration.ts
src/admin/resolvers/queries/ScheduledItem.ts
src/admin/resolvers/queries/ScheduledSurface.auth.integration.ts
src/admin/server.ts
src/database/helpers/checkCorpusUrl.ts
src/database/mutations/ApprovedItem.ts
src/database/queries/ScheduledItem.ts
src/public/resolvers/queries/ScheduledSurface.ts
src/public/server.ts
src/test/admin-server.ts

implement our custom error formatter.
- clean up a few other things
- some tests skipped as they do not yet work with our custom formatter
- shipping this - are any clients (curation admin tools, the backfill perhaps) relying on the existing error codes?
- ~skipping tests that deliberately trigger graph-level errors. our custom formatter cannot currently capture/identify these. is it okay to ship skipping these tests? would it be better to test for the existing (but incorrect) result of getting an `INTERNAL_SERVER_ERROR`?~ with kelvin's help, i worked around this issue and there are no longer any tests skipped.

chore(errors): use our custom error formatter from apollo-utils

---

src/public/resolvers/queries/ScheduledSurfaceItem.integration.ts
src/public/resolvers/queries/ScheduledSurfaceItem.ts

Investigate the public query that returned too many results (or, for Pocket Hits, results _at all_). 
- It turns out the `items` subquery within the `scheduledSurface` query never got the correct value for scheduled surface GUID. Now fixed.
- Added an integration tests that checks that the code is really fixed.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1433

fix(query): [BACK-1433] Public query returns too many results

---

schema-admin.graphql
schema-shared.graphql
src/admin/resolvers/index.ts
src/admin/resolvers/queries/ApprovedItem.integration.ts
src/admin/resolvers/queries/ApprovedItem.ts
src/admin/resolvers/queries/sample-queries.gql.ts
src/config/index.ts
src/database/queries/ApprovedItem.ts
src/database/queries/index.ts
src/database/types.ts

We need to add a query that retrieves scheduled entries for a corpus item. 
- Added a subquery to the admin schema.
- Added a resolver that takes in result limit + scheduled surface guid, both optional, and retrieves an array of scheduled items in return.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1439

feat(history): [BACK-1439] Add `scheduledSurfaceHistory` subquery to ApprovedItem

---

src/public/resolvers/queries/ScheduledSurfaceItem.integration.ts
src/public/resolvers/queries/sample-queries.gql.ts

This is a _verrry_ small fix to update integration tests for the public query - adding in authors and expecting to receive some data for them.

fix(authors): Update tests for public query

---

src/events/snowplow/ReviewedItemSnowplowHandler.integration.ts
src/events/snowplow/ReviewedItemSnowplowHandler.ts
src/events/types.ts

When going through the doc ticket ([#1422](https://getpocket.atlassian.net/browse/BACK-1422)) and referencing some code changes, I realised the initial updates to Curated Corpus API missed adding the authors to the data we send with Snowplow events. This ticket should fix that, and update relevant tests.
- Now sending names of authors as an array to Snowplow along with other data for reviewed corpus items. Updated tests.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1442

fix(authors): [BACK-1442] Add authors to Snowplow output

---

schema-public.graphql
src/database/queries/ScheduledItem.ts
src/database/types.ts
src/public/resolvers/queries/ScheduledSurfaceItem.integration.ts
src/public/resolvers/queries/sample-queries.gql.ts

add topic to public `CorpusItem` entity in preparation of need by recommendations/data products.
- update chai statements to use our preferred `exists` (but only in the one file i touched i'm not trying to do it all here)
- `topic` being a string in our graphql schema and not an enum. i personally think this is the right decision at this time, but would like to know if anyone disagrees.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1452

feat(add topic): add topic to public CorpusItem entity

---

src/database/queries/ApprovedItem.ts
src/database/queries/ScheduledItem.ts
src/public/resolvers/index.ts
src/public/resolvers/queries/CorpusItem.integration.ts
src/public/resolvers/queries/CorpusItem.ts
src/public/resolvers/queries/sample-queries.gql.ts
src/shared/utils.spec.ts
src/shared/utils.ts

Allow us to resolve Corpus Items, which is needed for the [setupMomentSlate](https://studio.apollographql.com/graph/pocket-client-api/schema/reference?variant=current#setupMomentSlate). This query will be used as part of an experiment in a couple weeks to show new Web users stories during onboarding.
Is there a better place for converting ApprovedItem to CorpusItem than utils.ts?
JIRA ticket:
* https://getpocket.atlassian.net/browse/HS-32
Documentation:
* [Spec PR #144](https://github.com/Pocket/spec/pull/144)
Apollo queries:
* [setupMomentSlate query with only an _id_ field](https://studio.apollographql.com/graph/pocket-client-api/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAMoIowAOAshIqiQDYCGKCRwAOkkUQM7kqteiiat2XHryJ4EUOvTCsAlhCR8O3adPl5KMPgEk2cTVO29lYLRYC%2BN3valPbIW0A& …

feat(resolvers): [HS-32] Resolve CorpusItem

---

schema-admin.graphql
src/admin/resolvers/index.ts
src/admin/resolvers/mutations/ApprovedItem.auth.integration.ts
src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/ApprovedItem.ts
src/admin/resolvers/mutations/sample-mutations.gql.ts
src/database/mutations/ApprovedItem.ts
src/database/mutations/index.ts
src/database/types.ts

Facilitate backfilling author information in the curated corpus. Initially we thought we could use the `updateApprovedCorpusItem` mutation, but that one requires `topic` to be set, which is something that many `DE` items don't yet have. So a custom mutation is needed, and it might as well take in only the data it actually needs rather than all editable fields of a curated item.
Note that a whole bunch of + X lines there, -Y lines here is me splitting out auth-related integration tests for approved items into their own file. 
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1475

feat(authors): [BACK-1475] Create a custom mutation to add authors to an approved item

---

schema-admin.graphql
src/admin/resolvers/index.ts
src/admin/resolvers/queries/ApprovedItem.auth.integration.ts
src/admin/resolvers/queries/ApprovedItem.integration.ts
src/admin/resolvers/queries/ApprovedItem.ts
src/admin/resolvers/queries/sample-queries.gql.ts
src/database/queries/index.ts
src/public/resolvers/queries/CorpusItem.integration.ts
src/public/resolvers/queries/CorpusItem.ts

Add a new query to unblock creating individual pages for curated items on the frontend.
- Added a new query to schema with a filter on `externalId`.
- Added integration tests.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1558

feat(query): [BACK-1558] Create a query to get a curated item by its `externalId`

---

src/config/index.ts
src/events/snowplow/ReviewedItemSnowplowHandler.integration.ts
src/events/snowplow/ReviewedItemSnowplowHandler.ts
src/events/snowplow/schema.ts

send `publisher` to snowplow for reviewed corpus items.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1553

chore(snowplow): add publisher to reviewed corpus item

---

prisma/migrations/20220829073134_make_topic_optional_for_rejected_items/migration.sql
prisma/schema.prisma
prisma/seed.ts
schema-admin.graphql
src/test/helpers/createApprovedItemHelper.ts
src/test/helpers/createRejectedCuratedCorpusItemHelper.ts
src/test/helpers/createScheduledItemHelper.ts

Until the corresponding frontend changes are ready to be merged, too: https://github.com/Pocket/curation-admin-tools/pull/943
Fix a long-running bug in the Curation Admin Tools when occasionally the Prospecting page crashes on fetching prospects.
- Updated GraphQL schema to make topic, publisher, title and language fields optional.
- Updated Prisma schema to make topic (the only field from the above list that was not yet optional) optional.
- Updated some Faker library calls to remove deprecated notices from integration tests.
JIRA ticket:
* https://getpocket.atlassian.net/browse/BACK-1492

feat(rejected items): [BACK-1492] Make fields optional on rejected items

---

.github/workflows/snowplow/schemas.json
src/shared/types.ts

Add a new prospecting source to the New Tab (US) surface as requested by the data products team. This source is already available for the Pocket Hits (US) surface. 
Similar to the Pocket Hits surfaces, I placed this source on top of the list in the API code. However, on the frontend, the sources are listed alphabetically, so this new source turns up on the list last (see screenshot below).
Additionally, the Snowplow schema check is failing for all PRs in this repository (`Invalid api key`). This won't fix it, but I thought I'd update the schema versions all the same - two out of three were well behind the current version.
JIRA ticket:
* https://getpocket.atlassian.net/browse/INFRA-965

feat(prospecting): [INFRA-965] Add new prospecting source (TOP_SAVED) to New Tab (US)

---

.circleci/config.yml
.circleci/scripts/setup.sh
.circleci/scripts/setup_db.sh
docker-compose.yml

Ticket: None, came up in context of CI fails on #830 
What this PR does:
* updates caching strategy in CircleCI to keep cache aligned with changes in packages & prisma config changes
* changes the CI steps for testing, builds to run on the same base image that the application itself is built upon & run within - to avoid differences in deployed environments & CI of OS-level requirements, like openssl versions installed

Updated CI Setup

---

schema-public.graphql
src/public/resolvers/index.ts
src/public/resolvers/queries/CorpusItem.integration.ts
src/public/resolvers/queries/CorpusItem.ts
src/public/resolvers/queries/sample-queries.gql.ts

Allow curated info to be available to saved items so we may create a consistent UX across surfaces.
- Create a connection for saved item by url
Everything!
Curated info is not available to saved items.  This creates opportunity for a confusion user experience because an item they save from one of our surfaces may end up being representing in an entirely different way once it gets to the save surface.  As we move down the path of blurring the lines between these surfaces with things like lists, it is important that we have the most relevant and consistent data available.
Here is a rather visceral example.

feat(saved): allow access to curated info on list

---

schema-public.graphql
src/public/resolvers/queries/CorpusItem.integration.ts
src/public/resolvers/queries/CorpusItem.ts

Setting up a url reference resolver that will be used to allow CorpusItem to be resolved by it's URL. This will be used on https://github.com/Pocket/list-api/pull/630 which will let clients know if the corpus item has been saved to the user's list.

feat(reference): adding a url based reference resolver for CorpusItem

---

schema-public.graphql
src/database/types.ts
src/public/resolvers/index.ts
src/public/resolvers/queries/CorpusItem.integration.ts
src/public/resolvers/queries/sample-queries.gql.ts
src/shared/utils.ts

Fix https://sentry.io/organizations/pocket/issues/3911297928/?project=5938284&query=is%3Aunresolved&referrer=issue-stream
Turns out that the main type (in this case CorpusTarget) comes into resolveType, and we are already defining the CorpusTarget slug elsewhere, we just needed to pass the type name with it.

fix(target): updating resolver for target type

---

docker-compose.yml
schema-shared.graphql
src/admin/resolvers/mutations/ApprovedItem.integration.ts
src/admin/resolvers/mutations/RejectedItem.integration.ts
src/main.ts

Adding Italian, Spanish and French languages to `CorpusLanguage` enum. Adding some more testing around this.
Updated docker-compose to use node18 for app container.
Adding the new language enum values under the `@inaccessible` directive. Once deployed, I will do a staggered deploy on the **prospect-api** side. 
This aligns with the what the docs mention for this directive: https://www.apollographql.com/docs/federation/federated-types/federated-directives/#inaccessible
This needs to be merged into prod first for the **prospect-api** PR apollo checks to pass. Since our `apollo` CircleCI orb only checks against the prod federated graph. I deployed both services to dev to test but need to tweak the orb for that first.
* [https://getpocket.atlassian.net/browse/INFRA-1017](https://getpocket.atla …

feat(CorpusLanguage): [INFRA-1017] Adding Italian, French, Spanish langauges to CorpusLanguage enum

---

schema-shared.graphql

Remove the `@inaccessible` schema directive from the newly added `CorpusLanguage` enum as the final part of the staggered update.
Related PRs:
https://github.com/Pocket/curated-corpus-api/pull/846
https://github.com/Pocket/prospect-api/pull/544
JIRA ticket:
* INFRA-1017

feat(CorpusLanguage): [INFRA-1017] Remove inaccessible directive from CorpusLanguage enum

---

.aws/package-lock.json
.aws/package.json
.aws/src/main.ts

Jira ticket: https://getpocket.atlassian.net/browse/INFRA-1276
**What this PR does:**
Adds some synthetic checks, using baseline of reusable code from monitoring "project" work, for sake of monitoring curated corpus api better in service of New Tab.
**Why this PR:**
New Tab is ... going live? Doing something important this week <New Tab folks to fill in>. As part of this, they requested that all services New Tab depends on are better supported operationally ASAP. Alas, Curated Corpus API's operational ownership falls currently to Backend.
As part of trying to be at least a little bit more prepared operationally, this PR adds a few synthetic checks to better monitor deployed Curated Corpus API codepaths that are vital for New Tab: the scheduledSurface Query, and something to do with …

feat(synchecks): add basic synchecks for graphql, server

---

.aws/src/main.ts

Enable tier 1 / critical alerting for the production synthetic checks, as they've been pushed to prod and appear to work as desired.
Related service & reliability docs: https://getpocket.atlassian.net/wiki/spaces/PE/pages/2561343516/Curated+Corpus+API
Closes out #908 & related ticket.

feat(synchecks): enable critical (tier 1) alerting on prod synchecks

---

.aws/src/config/index.ts

Experiment with increasing Aurora capacity, to see if it fixes errors from Prisma:
- [Timed out fetching a new connection from the connection pool.](https://pocket.sentry.io/issues/4397585063/?query=start%3D2023-08-19T08%3A57%3A00%26end%3D2023-08-19T23%3A40%3A53%26groupStatsPeriod%3Dauto&referrer=alerts-related-issues-issue-stream) More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)
- [Incorrect arguments to mysqld_stmt_execute](https://pocket.sentry.io/issues/4397585063/?query=start%3D2023-08-19T08%3A57%3A00%26end%3D2023-08-19T23%3A41%3A42%26groupStatsPeriod%3Dauto&referrer=alerts-related-issues-issue-stream)
Both of these errors spiked immediately after a scale-in event from 2 to 1 capacity units on Aurora Serverless.
JIRA ticket:
* …

fix(RDS): Increase minCapacity on production from 1 to 2

---

.aws/src/main.ts

Enable prisma query logging
-  Did I get it right
Because we use the event model for prisma client, all queries are sent to our Winston logging instance. These are delivered as 'debug' log level. The correct way to enable query logging for this app is to set the log level to debug.
```
export function client(): PrismaClient {
if (prisma) return prisma;
prisma = new PrismaClient({
log: [
{
level: 'error',
emit: 'event',
},
{
level: 'warn',
emit: 'event',
},
{
level: 'info',
emit: 'event',
},
{
level: 'query',
emit: 'event',
},
],
});
prisma.$on('error', (e) => {
e.source = 'prisma';
serverLogger.error(e);
});
prisma.$on('warn', (e) => {
e.source = 'prisma';
serverLogger.warn(e);
});
prisma.$on('info', (e) => {
e.source = 'prisma';
serverLogger.info(e);
});
prisma.$on('query', (e) => { …
```

Enable prisma query logging

---

.aws/src/main.ts

This reverts commit ba5f8d6b1acf3546bd17f4654c5e348d468b012e.
It appears that https://github.com/Pocket/curated-corpus-api/pull/997 accidentally disables all logging. I tested this locally, but should have tested it in our dev environment.
My guess is that changing `debug` to `DEBUG` might fix the issue, but I'd rather test this in dev first.

Revert "feat(Database): enable prisma query logging (#997)"

---

schema-admin.graphql
src/shared/types.ts

This is for https://mozilla-hub.atlassian.net/browse/MC-144 
We are adding a new prospecting source for the curators for US new tab and pocket hits
Related PRs
https://github.com/Pocket/dl-metaflow-jobs/pull/227 and https://github.com/Pocket/prospect-api/pull/566

Added new RSS feed content prospecting type

---

.aws/src/main.ts

Previously per object ACL access defaulted to 'on' for new s3 buckets, but at some point that changed.
https://mozilla-hub.atlassian.net/browse/MC-230
Due to a bucket re-creation, the Dev environment bucket has no permissions for public image hosting, causing the 'add to corpus' feature to no longer work on Dev.
This was tested by pushing to dev and it didn't seem to re-create the bucket -- it modified the permissions. Prod push for this PR should be monitored.

Change default ACLs for image upload public bucket

---

.aws/src/main.ts

Save cost and emissions by lowering the number of tasks running in our Dev environment.
[Slack thread](https://mozilla.slack.com/archives/C05UHBNS1HV/p1697572493007419)

chore: lower dev min task count from 4 to 1

---

schema-admin.graphql
src/shared/types.ts

Add the new `RSS_LOGISTIC_RECENT` prospect type to `NEW_TAB_EN_US` surface for the new tab recent content experiment.
Will be merged before this [PR](https://github.com/Pocket/prospect-api/pull/572).
JIRA ticket:
* [MC-318](https://mozilla-hub.atlassian.net/browse/MC-318)
[MC-318]: https://mozilla-hub.atlassian.net/browse/MC-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(OGExcerpt): [MC-318] Add rss_logistic_recent prospect type to new_tab_en_us
